config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users
  
  resources :users do
    member do
      get :profile
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :posts do
    collection do
      get :pinned
      get :announcements
    end
    resources :comments do
      member do
        post :like
        delete :unlike
      end
    end
    member do
      post :like
      delete :unlike
      post :pin
      delete :unpin
    end
  end

  resources :topics
  resources :uploaded_files
  resources :subscriptions, only: [:create, :destroy]

  get 'help', to: 'pages#help'
  post 'direct_uploads', to: 'direct_uploads#create'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comment_likes, dependent: :destroy
  has_many :liked_comments, through: :comment_likes, source: :comment
  has_many :notifications, as: :recipient, dependent: :destroy
  
  has_many :subscriptions_as_subscriber, class_name: 'Subscription', foreign_key: 'subscriber_id', dependent: :destroy
  has_many :subscriptions_as_poster, class_name: 'Subscription', foreign_key: 'poster_id', dependent: :destroy
  has_many :subscribers, through: :subscriptions_as_poster, source: :subscriber
  has_many :subscribed_to, through: :subscriptions_as_subscriber, source: :poster
  has_one_attached :profile_picture
  has_rich_text :bio

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validate :correct_profile_picture_mime_type

  def subscriptions
    subscriptions_as_subscriber
  end

  def subscribed_users
    subscribed_to
  end

  private

  def correct_profile_picture_mime_type
    if profile_picture.attached? && !profile_picture.content_type.in?(%w[image/png image/jpg image/jpeg])
      errors.add(:profile_picture, 'must be a PNG, JPG, or JPEG file')
      profile_picture.purge
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_picture, :bio])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ profile edit update destroy subscribe unsubscribe ]
  before_action :check_admin!, only: %i[ edit update destroy ]
  def profile
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_profile_path, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    redirect_to root_path, notice: "User was successfully destroyed."
  end

  def subscribe
    current_user.subscriptions.create(subscriber_id: current_user.id, poster_id: @user.id)
    redirect_to profile_user_path, notice: "You are now subscribed to this user."
  end

  def unsubscribe
    current_user.subscriptions.find_by(poster_id: @user.id).destroy
    redirect_to profile_user_path, notice: "You are no longer subscribed to this user."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def check_admin!
    unless current_user.admin?
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_picture, :bio)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<h1>Edit User Profile</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions update-profile">
    <%= form.submit "Update Profile" %>
  </div>
<% end %>

app/views/users/profile.html.erb
<h1 class="profile-header">User Profile</h1>

<div class="profile-card">
  <div class="profile-picture">
    <% if @user.profile_picture.attached? %>
      <%= image_tag @user.profile_picture.variant(resize_to_limit: [150, 150]), class: "profile-image" %>
    <% else %>
      <i class="bi bi-person-circle default-profile-icon"></i>
    <% end %>
  </div>

  <div class="profile-details">
    <p class="profile-detail">
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p class="profile-detail">
      <strong>Bio:</strong>
      <%= @user.bio.presence || "No bio available" %>
    </p>

    <p class="profile-detail">
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p class="profile-detail">
      <strong>Joined:</strong>
      <%= @user.created_at.strftime("%B %d, %Y") %>
    </p>

    <% if current_user.admin? %>
      <div class="admin-actions">
        <%= link_to "Edit", edit_user_path(@user), class: "btn mt-2" %>
        <%= link_to "Delete", @user, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger mt-2" %>
      </div>
    <% end %>

    <p class="profile-detail">
      <strong>Posts:</strong>
      <%= @user.posts.count %>
    </p>
  </div>
</div>

<div class="user-posts">
  <% @user.posts.each do |post| %>
    <div class="post-card" onclick="location.href='<%= post_path(post) %>';">
      <h3 class="post-title"><%= post.title %></h3>
      <p class="post-excerpt"><%= truncate(post.body.to_plain_text, length: 100) %></p>
      <p class="post-meta">Published <%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
  <% end %>
</div>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Joined:</strong>
  <%= @user.created_at.strftime("%B %d, %Y") %>
</p>

<div>
  <% if current_user.subscribed_users.include?(@user) %>
    <%= button_to "Unsubscribe", unsubscribe_user_path(@user), method: :delete, class: "btn btn-warning" %>
  <% else %>
    <%= button_to "Subscribe", subscribe_user_path(@user), method: :post, class: "btn btn-primary" %>
  <% end %>
</div>

<%# if current_user&.liked_posts&.include?(post) %>
  <%#= button_to 'Unlike', unlike_post_path(post), method: :delete, class: 'btn btn-warning mt-2' %>
<%# else %>
  <%#= button_to 'Like', like_post_path(post), method: :post, class: 'btn btn-primary mt-2' %>
<%# end %>

<% if current_user.admin? %>
  <div class="button-group">
    <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
    <%= link_to "Delete", @user, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>