config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users
  
  resources :users do
    member do
      get :profile
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :posts do
    collection do
      get :pinned
      get :announcements
    end
    resources :comments do
      member do
        post :like
        delete :unlike
      end
    end
    member do
      post :like
      delete :unlike
      post :pin
      delete :unpin
    end
  end

  resources :topics
  resources :uploaded_files
  resources :subscriptions, only: [:create, :destroy]

  get 'help', to: 'pages#help'
  post 'direct_uploads', to: 'direct_uploads#create'
end

app/views/shared/_topics.html.erb
<div class="card mb-4">
  <div class="card-header">
    <h5 class="card-title mb-0">Topics</h5>
  </div>
  <div class="card-body">
    <div class="list-group">
      <%= link_to "All Posts", posts_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "Pinned Posts", pinned_posts_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "Announcements", announcements_posts_path, class: "list-group-item list-group-item-action" %>
      <% Topic.all.each do |topic| %>
        <%= link_to topic.name, topic_path(topic), class: "list-group-item list-group-item-action" %>
      <% end %>
<h1>Topics</h1>

<% if current_user&.admin? %>
  <a class="btn add-new-topic" href="<%= new_topic_path %>">
    <i class="bi bi-plus"></i> Add New Topic
  </a>
<% end %>


<a class="btn mt-2" href="<%= pinned_posts_path %>">
  <i class="bi bi-pin-fill"></i>
  All Pinned Posts
</a>

<div class="topics-container">
<% @topics.each do |topic| %>

  <% if current_user&.admin? %>

    <div class="btn-group mt-2 topic">
      <a href="<%= posts_path(topic_id: topic.id) %>" class="btn btn-sm btn-outline-light dontbecomeinviswhenhovered ">
        <strong>
          <%= topic.name %>
        </strong> <br>
        <%= topic.description %>
      </a>
      <div class="btn-group-vertical">
        <a href="<%= edit_topic_path(topic) %>" class="btn btn-sm btn-outline-light dontbecomeinviswhenhovered" style="border-top-left-radius: 0">
          Edit
        </a>
        <%= link_to "Delete", topic, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-light dontbecomeinviswhenhovered", style: "border-bottom-left-radius: 0" %>
        </a>
      </div>
    </div>
  </div>
</div>