config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users
  
  resources :users do
    member do
      get :profile
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :posts do
    collection do
      get :pinned
      get :announcements
    end
    resources :comments do
      member do
        post :like
        delete :unlike
      end
    end
    member do
      post :like
      delete :unlike
      post :pin
      delete :unpin
    end
  end

  resources :topics
  resources :uploaded_files
  resources :subscriptions, only: [:create, :destroy]

  get 'help', to: 'pages#help'
  post 'direct_uploads', to: 'direct_uploads#create'
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice" style="color: green"><%= notice %></p>
<% elsif alert %>
  <p class="alert" style="color: red"><%= alert %></p>
<% end %>

app/views/layouts/_notifications.html.erb
<% if current_user %>
  <div class="dropdown">
    <button class="btn btn-link" type="button" id="notificationsDropdown" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="fas fa-bell"></i>
      <% if current_user.notifications.unread.any? %>
        <span class="badge bg-danger"><%= current_user.notifications.unread.count %></span>
      <% end %>
    </button>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationsDropdown">
      <% if current_user.notifications.any? %>
        <% current_user.notifications.order(created_at: :desc).limit(5).each do |notification| %>
          <div class="dropdown-item">
            <%= notification.params&.dig('message') || 'New notification' %>
            <small class="text-muted d-block"><%= time_ago_in_words(notification.created_at) %> ago</small>
          </div>
        <% end %>
      <% else %>
        <div class="dropdown-item">No notifications</div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
<head>
  <title><%= content_for(:title) || "Acuai" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">
  <link href=" https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/minty/bootstrap.min.css " rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%#= javascript_include_tag "turbo", type: "module" %>
  <%= javascript_importmap_tags %>
</head>

<body class="not-scrollable">
<main class="container-fluid">
  <header>
  <nav class="bg-primary navbar navbar-expand-lg" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="<%= asset_path('ACUAI.png') %>" alt="ACUAI" class="rounded">
    </a>
    <a class="navbar-brand" href="<%= root_path %>">ACUAI</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= uploaded_files_path %>">Files</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= help_path %>">How to Use</a>
        </li>
      </ul>

      <div class="d-flex me-auto">
        <%= form_with url: posts_path, method: :get, local: true, html: { class: "d-flex" } do %>
          <div class="input-group">
            <span class="input-group-text">
              <i class="bi bi-search"></i>
            </span>
            <%= hidden_field_tag :topic_id, params[:topic_id] if params[:topic_id].present? %>
            <%= hidden_field_tag :order, params[:order] if params[:order].present? %>
            <%= text_field_tag :search, params[:search], class: "form-control", id:"navv", placeholder:  "Search Posts" %>
            <%= submit_tag "Search", class: "btn btn-dark" %>
          </div>
        <% end %>

        <% if user_signed_in? %>
          <a class="btn ms-2" style="background: #003D7E" href="<%= new_post_path %>">
            <i class="bi bi-plus-circle-fill"></i>
            New Post
          </a>
          <a class="btn ms-2" style="background: #003D7E" href="<%= new_uploaded_file_path %>">
            <i class="bi bi-file-arrow-up-fill"></i>
            Upload File
          </a>
          <div class="ms-2">

          <%= render "layouts/notifications" %>
          </div>

          <div class="navbar-profile-picture ms-2">
              <% if current_user.profile_picture.attached? %>
                <%= image_tag current_user.profile_picture.variant(resize_to_limit: [50, 50]), id: "navbar_profile_picture" %>
              <% else %>
              <i class="bi bi-person-circle"></i>
              <% end %>
            </div>
          <div class="dropdown ms-2">
            <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.admin? %>
                <i class="bi bi-shield-fill" style="color: yellow"></i>
                Admin: <%= current_user.name %>
              <% else %>
                <i class="bi bi-person-circle"></i>
                <%= current_user.name %>
              <% end %>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="dropdownMenuLink">
              <li>
                <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "See Profile", profile_user_path(current_user), class: "dropdown-item" %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>

      <% if user_signed_in? %>
        <a class="btn ms-2" href="<%= new_post_path %>">
          <i class="bi bi-plus-circle-fill"></i> New Post
        </a>
        <a class="btn ms-2" href="<%= new_uploaded_file_path %>">
          <i class="bi bi-file-arrow-up-fill"></i> Upload File
        </a>
        <div class="user-dropdown ms-2">
  <a class="btn dropdown-toggle user-dropdown-btn" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    <% if current_user.admin? %>
      <i class="bi bi-shield-fill" style="color: yellow"></i> Admin: <%= current_user.name %>
    <% else %>
      <i class="bi bi-person-circle"></i> <%= current_user.name %>
    <% end %>
  </a>
  <ul class="dropdown-menu dropdown-menu-lg-end user-dropdown-menu" aria-labelledby="dropdownMenuLink">
    <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item user-dropdown-item" %></li>
    <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item user-dropdown-item" %></li>
    <li><%= link_to "See Profile", profile_user_path(current_user), class: "dropdown-item user-dropdown-item" %></li>
  </ul>
</div>

      <% else %>
        <a class="btn ms-2" href="<%= new_user_session_path %>">Log in</a>
        <a class="btn ms-2" href="<%= new_user_registration_path %>">Sign up</a>
      <% end %>
    </div>
  </div>
</nav>

  </header>
  <div class="row justify-content-center not-scrollable">
    <div class="col-2 scrollable">
      <%= render "shared/topics" %>
    </div>
    <div class="container col outlined">
      <div class=" scrollable">
        <%= render "layouts/alerts" %>
        <%= yield %>
      </div>
    </div>
    <div class="col-3 scrollable ">
      <%= render 'posts/announcements' %>
    </div>
  </div>
</main>
</body>
</html>